language: bash

sudo: false

os:
  - linux
  - linux-ppc64le

services:
  - docker

env:
  - Dockerfile=v0.12/alpine
  - Dockerfile=v0.12/debian
  - Dockerfile=v1.5/alpine
  - Dockerfile=v1.5/debian

before_script:
  - make image DOCKERFILE=$Dockerfile VERSION=test

script:
  - make test DOCKERFILE=$Dockerfile VERSION=test
